# Generated by Django 4.2.24 on 2025-09-13 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sendonce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendallowance',
            options={'ordering': ('-remaining',), 'verbose_name': 'Пользователи рассылки', 'verbose_name_plural': 'Пользователи рассылки'},
        ),
        migrations.AddField(
            model_name='sendallowance',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя в вк'),
        ),
        migrations.AlterField(
            model_name='sendallowance',
            name='remaining',
            field=models.IntegerField(default=0, verbose_name='Количество доступных попыток'),
        ),
        migrations.AlterField(
            model_name='sendallowance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Юзер', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='логин юзера'),
        ),
    ]
